name: ci

on:
  push:
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1

      - uses: pawnkit/pawn-actions/setup@v1.8.72
        with:
          version: 1.34.29
          download-url: https://github.com/pawnkit/pawnkit-cli/releases/download/v1.34.29/pawn-linux-amd64.tar.gz
          sha256: 7de00c510c1beb9de66fb2554ceb5314e41e5fec86a46a2626f65a22c038ce61

      - name: Install dependencies
        env:
          GH_TOKEN: ${{ github.token }}
        run: pawn install

      - uses: pawnkit/pawn-actions/build@v1.8.72
