name: ci

on:
  push:
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1

      - uses: pawnkit/pawn-actions/setup@v1.8.25
        with:
          version: 1.34.0
          download-url: https://github.com/pawnkit/pawnkit-cli/releases/download/v1.34.0/pawn-linux-amd64.tar.gz
          sha256: 08832cb8e2cf2ea9a660cf42df4f2db93be160dd2b955a4c44e234b51451f374

      - name: Install dependencies
        env:
          GH_TOKEN: ${{ github.token }}
        run: pawn install

      - uses: pawnkit/pawn-actions/build@v1.8.25
