name: ci

on:
  push:
  pull_request:
    branches: [master]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.1

      - uses: pawnkit/pawn-actions/setup@v1.8.25
        with:
          version: 1.33.0
          download-url: https://github.com/pawnkit/pawnkit-cli/releases/download/v1.33.0/pawn-linux-amd64.tar.gz
          sha256: 01feebf5bf0cb89b752f7a4002b132c8efa1c78c3e9ac26319a16f7e5c074db3

      - name: Install dependencies
        env:
          GH_TOKEN: ${{ github.token }}
        run: pawn install

      - uses: pawnkit/pawn-actions/build@v1.8.25
